import type {NextPage} from 'next'
import Head from 'next/head'
import Search from "../components/index/search";
import PostListItem from "../components/post/PostListItem";
import React, {useContext, useEffect} from "react";
import {AxiosContext} from "../contexts/axiosContext";
import {AxiosContextType} from "../@types/axiosContextType";
import {getPosts, Post} from "../API/post.api";
import {useQuery} from "react-query";
import Spinner from "../components/common/spinner";
import Heading from "../components/common/heading";
import SideAlert from "../components/alerts/sideAlert";
import {GENERIC_ALERT} from "../constants";


const Home: NextPage = () => {

    const titleTypes = [
        {key: "1", value: "School/College"},
        {key: "2", value: "Security"},
        {key: "3", value: "IT"},
        {key: "4", value: "Banking"},
        {key: "5", value: "Receptionist"},
    ]

    const positionTypes = [
        {key: "1", value: "Teacher"},
        {key: "2", value: "Driver"},
        {key: "3", value: "Developer"},
        {key: "4", value: "Backend"}
    ]

    const {axiosInstance} = useContext(AxiosContext) as AxiosContextType

    const {data, isLoading} = useQuery("posts", fetchPosts, {enabled: axiosInstance != null, retryOnMount: true})

    const posts = data?.data as Post[]

    function fetchPosts() {
        return getPosts(axiosInstance)
    }

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>

            <div className={"flex flex-col justify-center w-full"}>
                <Search/>
            </div>

            <main>
                <Heading heading={"All Jobs"} count={posts ? posts.length : 0} sort={true} />

                <div>
                    {isLoading && <Spinner />}
                    {posts?.map((post, i) => (
                        <PostListItem key={i} post={post}/>
                    ))}
                </div>
            </main>

        </div>
    )
}

export default Home
